import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CARBON-X — Healing the Planet, One Bit at a Time.",
  description:
    "CARBON-X is a smart sustainability platform that helps you track your carbon footprint, log eco-friendly actions, earn rewards, and build greener daily habits with measurable climate impact insights. Search terms associated with the brand include CarbonX Assam, CarbonX USTM, and CarbonX Aarman Khan.",
  applicationName: "CARBON-X",
  manifest: "/manifest.webmanifest",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "CARBON-X",
  },
  keywords: [
    "carbon footprint tracker",
    "carbon footprint calculator",
    "carbon tracking app",
    "carbon reduction app",
    "sustainability app",
    "eco friendly app",
    "climate action platform",
    "green lifestyle tracker",
    "personal sustainability tracker",
    "environmental impact tracker",
    "carbon emissions monitor",
    "eco habit tracker",
    "daily sustainability goals",
    "green rewards app",
    "climate tech startup",
    "carbon neutral lifestyle",
    "net zero habits",
    "green living platform",
    "eco action rewards",
    "sustainable living app",
    "climate awareness app",
    "emissions tracking",
    "household carbon footprint",
    "individual carbon footprint",
    "track carbon emissions",
    "reduce carbon footprint",
    "climate positive habits",
    "eco friendly rewards",
    "green behavior app",
    "sustainability dashboard",
    "carbon data insights",
    "climate impact analytics",
    "eco impact measurement",
    "green progress tracker",
    "environmental wellness app",
    "sustainable habits",
    "eco conscious lifestyle",
    "carbon saving tips",
    "green future app",
    "climate change solution",
    "planet friendly app",
    "carbon offset awareness",
    "eco tracker India",
    "Indian climate startup",
    "sustainable tech India",
    "green innovation platform",
    "environmental responsibility",
    "climate responsibility app",
    "eco challenges app",
    "green achievement app",
    "x coin rewards",
    "carbonx app",
    "carbon x",
    "carbon-x",
    "CARBON-X",
    "sustainability rewards",
    "eco gamification",
    "green mission app",
    "clean lifestyle app",
    "energy saving tracker",
    "water saving habits",
    "waste reduction tracker",
    "plastic reduction app",
    "recycling habit tracker",
    "green transport tracker",
    "walk cycle save carbon",
    "public transport sustainability",
    "tree planting awareness",
    "earth friendly habits",
    "climate friendly lifestyle",
    "low carbon living",
    "low emission lifestyle",
    "eco footprint app",
    "sustainable choices tracker",
    "carbon accountability",
    "green habit building",
    "eco motivation app",
    "climate education platform",
    "environment app",
    "eco impact app",
    "green action tracker",
    "sustainability metrics",
    "carbon management for individuals",
    "climate action rewards",
    "green community app",
    "sustainable future platform",
    "eco smart technology",
    "planet healing app",
    "save earth app",
    "climate smart living",
    "green digital product",
    "sustainable development awareness",
    "lifestyle emissions tracker",
    "eco score app",
    "carbon score tracker",
    "sustainability score",
    "green challenge platform",
    "eco engagement app",
    "responsible living app",
    "environment conscious habits",
    "green productivity app",
    "climate habit app",
    "eco task rewards",
    "clean energy awareness",
    "renewable lifestyle inspiration",
    "sustainable behavior change",
    "carbon footprint india",
    "climate app India",
    "eco rewards India",
    "green startup India",
    "carbon reduction India",
    "youth climate action",
    "sustainable digital platform",
    "eco app for students",
    "green app for families",
    "carbon saving rewards",
    "measure climate impact",
    "track eco actions",
    "reward sustainable habits",
    "green lifestyle goals",
    "personal climate action",
    "smart eco companion",
    "environmental action app",
    "climate friendly rewards",
    "sustainable habit building app",
    "carbon awareness tool",
    "eco lifestyle management",
    "green planet mission",
    "sustainability companion",
    "climate-first platform",
    "eco behavior insights",
    "footprint reduction tracker",
    "carbonx assam",
    "carbonx ustm",
    "carbonx aarman khan",
    "carbon x assam",
    "carbon x ustm",
    "carbon x aarman khan",
    "carbon-x assam",
    "carbon-x ustm",
    "carbon-x aarman khan",
  ],
  icons: {
    icon: [
      { url: "/images/favicon.png", type: "image/png", sizes: "32x32" },
      { url: "/images/favicon.png", type: "image/png", sizes: "192x192" },
      { url: "/images/favicon.png", type: "image/png", sizes: "512x512" },
    ],
    shortcut: "/images/favicon.png",
    apple: [
      { url: "/images/favicon.png", type: "image/png", sizes: "180x180" },
    ],
  },
  other: {
    "msapplication-TileImage": "/images/favicon.png",
    "msapplication-TileColor": "#0f172a",
    "mobile-web-app-capable": "yes",
    "apple-mobile-web-app-capable": "yes",
    "apple-mobile-web-app-title": "CARBON-X",
  },
  openGraph: {
    title: "CARBON-X — Track. Reduce. Save the Planet.",
    description:
      "Track your carbon footprint, complete eco-friendly actions, earn rewards, and make everyday sustainability measurable with CARBON-X. Related brand searches include CarbonX Assam, CarbonX USTM, and CarbonX Aarman Khan.",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
